### ISSUE TITLE
Show link to Bluesky even when there are no comments

### ISSUE THREAD

**Issue by lucas-a-meyer** [gadenbuie/quarto-bluesky-comments#3]
Currently, if there are no comments, the extension will show something like "Error: No comments found" even though a Bluesky post is already linked to the Quarto post.

Suggestion: if there are no comments in the Quarto post yet, still show the likes, reposts and the link where people can click to go to Bluesky to add comments.

This works well especially if you post announcements of blog posts in multiple social networks - people who are not in Bluesky can at least see that they can go to Bluesky to comment.

The implementation is simple: we just need to delete code 😄 , specifically this code in the `render()` function:

```
    if (!sortedReplies || sortedReplies.length === 0) {
      this.renderError('No comments found')
      return
    }
```

Here's an example of how it looks when there are no comments. For me, the best part is to be able to have the link "Reply on Bluesky to join the conversation."

![image](https://github.com/user-attachments/assets/71522b86-489a-479e-9708-ba4739567fa7)

I wrote the code and tested it locally but couldn't do a pull request.

**Comment by gadenbuie** [comment]
Great point, thanks for opening the issue! I just pushed a fix (let me know if it gives you any issues).

Just a note -- I'm working on merging this extension with another version released at the same time by James Balamuta. We're consolidating the work into https://github.com/quarto-ext/bluesky-comments. We plan to have feature parity soon and I do intend for the transition to be seamless. I'll post in #2 when that transition is complete with migration guidance.
